FROM python:3.12-slim

WORKDIR /app

COPY ./chelonest/docker/heuristics/requirements.txt /app/
RUN pip install -r requirements.txt

COPY ./chelonest/docker/detector/.env /app/
COPY ./chelonest/docker/detector/run.sh /app/run.sh

COPY ./chelonest/chelonest_config.py /app/
COPY ./chelonest/chelonest_heuristic*.py /app/
COPY ./chelonest/plugins /app/

RUN chmod +x /app/*.sh

VOLUME ["/data"]

CMD ["/app/run.sh"]
