FROM python:3.12-slim

#RUN apk add --no-cache ttf-dejavu busybox-extras

WORKDIR /app

RUN apt-get update
RUN apt-get install -y libxcb1 libgl1

COPY ./chelonest/docker/detector/requirements.txt /app/
RUN pip install -r requirements.txt

COPY ./chelonest/docker/detector/.env /app/
COPY ./chelonest/docker/detector/run.sh /app/run.sh

COPY ./chelonest/chelonest_config.py /app/
COPY ./chelonest/chelonest_detector.py /app/
COPY ./chelonest/chelonest_watchdog.py /app/

RUN chmod +x /app/*.sh

VOLUME ["/data"]

CMD ["/app/run.sh"]
