FROM python:3.12-alpine

#RUN apk add --no-cache ttf-dejavu busybox-extras

WORKDIR /app

COPY ./chelonest/docker/detector/requirements.txt /app/
RUN pip install -r requirements.txt

COPY ./chelonest/docker/detector/.env /app/
COPY ./chelonest/docker/detector/run.sh /app/run.sh

COPY ./chelonest/chelonest_config.py /app/
COPY ./chelonest/vhelonest_detector.py /app/
COPY ./chelonest/chelonest_detector_watchdog.py /app/

RUN chmod +x /app/*.sh

VOLUME ["/data"]

CMD ["/app/run.sh"]
